; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit MPL3115A2 Library@^2.1.2
	robtillaart/MS5611@^0.4.1
	nanopb/Nanopb@^0.4.91
	adafruit/Adafruit LSM6DS@^4.7.4
	mikalhart/TinyGPSPlus@^1.1.0
	adafruit/SdFat - Adafruit Fork@^2.2.54
	adafruit/Adafruit SSD1306@^2.5.14
	adafruit/Adafruit GFX Library@^1.11.10
	adafruit/Adafruit NeoPixel@^1.11.0
	jgromes/RadioLib@^7.1.2

[env:default]
build_src_filter = +<main.cpp> +<../systems/*/src/*>

[env:vehicle]
build_src_filter = -<main.cpp> +<vehicle_main.cpp>

[env:vehicle_v4]
build_src_filter = -<main.cpp> +<vehicle_main.cpp>
build_flags = -DBOARD_V4 -DARDUINO_USB_CDC_ON_BOOT=1

[env:ground_station]
build_src_filter = -<main.cpp> +<ground_main.cpp>

[env:i2c]
build_src_filter = -<main.cpp> +<../systems/i2c/*>

[env:gps]
build_src_filter = -<main.cpp> +<../systems/gps/*>

[env:gps_v4]
build_src_filter = -<main.cpp> +<../systems/gps/*>
build_flags = -DBOARD_V4 -DARDUINO_USB_CDC_ON_BOOT=1

[env:sd]
build_src_filter = -<main.cpp> +<../systems/sd/*>

[env:oled]
build_src_filter = -<main.cpp> +<../systems/oled/*>

[env:gps_passthrough]
build_src_filter = -<main.cpp> +<../systems/gps_passthrough/*>

[env:radio]
build_src_filter = -<main.cpp> +<../systems/radio/*>

[env:logger]
build_src_filter = -<main.cpp> +<../systems/logger/*>

[env:lora]
build_src_filter = -<main.cpp> +<../systems/lora/*>

[env:imu]
build_src_filter = -<main.cpp> +<../systems/imu/*>

[env:ms5611]
build_src_filter = -<main.cpp> +<../systems/MS5611/*>

[env:bmi160]
build_src_filter = -<main.cpp> +<../systems/bmi160/*>

[env:bmi160_calibration]
build_src_filter = -<main.cpp> +<../systems/bmi160_calibration/*>

[env:ground_wio]
platform = nordicnrf52
board = WioTrackerL1_companion_radio_ble
framework = arduino
monitor_speed = 115200
board_build.variants_dir = variants
upload_protocol = nrfutil
board_build.ldscript = variants/WioTrackerL1_companion_radio_ble/nrf52840_s140_v7.ld
build_src_filter = -<main.cpp> +<ground_wio_main.cpp>
extra_scripts = post:uf2_build.py
lib_deps =
	jgromes/RadioLib@^7.1.2
	zinggjm/GxEPD2@^1.6.4
	adafruit/Adafruit GFX Library@^1.11.10
	adafruit/Adafruit BusIO@^1.16.2