/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_DATA_PB_H_INCLUDED
#define PB_SENSOR_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Rocket error codes */
typedef enum _RocketError {
    RocketError_NONE = 0,
    RocketError_UNKNOWN = 999,
    RocketError_SD_INIT_ERROR = 9,
    RocketError_GPS_INIT_ERROR = 10,
    RocketError_ACCEL_INIT_ERROR = 11,
    RocketError_GYRO_INIT_ERROR = 12,
    RocketError_MAG_INIT_ERROR = 13,
    RocketError_BARO_INIT_ERROR = 14,
    RocketError_BATTERY_INIT_ERROR = 15,
    RocketError_BATTERY_VOLTAGE_LOW = 20
} RocketError;

/* Device status flags */
typedef enum _RocketState {
    /* Unknown/default state */
    RocketState_ERROR = 0,
    /* Device Initialization */
    RocketState_INITIALIZING = 1, /* Software initialization */
    RocketState_WAITING_ON_GPS = 2, /* Waiting for GPS fix */
    /* Pre-launch states */
    RocketState_PAD_IDLE = 10, /* On pad, not armed */
    RocketState_ARMED = 11, /* On pad, armed and ready for launch */
    RocketState_COUNTDOWN = 12, /* Countdown sequence initiated */
    /* Flight states */
    RocketState_IGNITION = 20, /* Motor ignition detected */
    RocketState_LIFTOFF = 21, /* Positive vertical movement detected */
    RocketState_ASCENT = 22, /* Under motor thrust */
    RocketState_APOGEE = 25, /* Maximum altitude reached */
    /* Deployment states */
    RocketState_DROGUE_DEPLOYMENT = 30, /* Drogue parachute deployment */
    RocketState_MAIN_DEPLOYMENT = 31, /* Main parachute deployment */
    RocketState_DUAL_DEPLOY = 32, /* Both chutes deployed */
    /* Descent states */
    RocketState_BALLISTIC = 40, /* Falling without parachute */
    RocketState_DROGUE_DESCENT = 41, /* Descending under drogue chute */
    RocketState_MAIN_DESCENT = 42, /* Descending under main chute */
    /* Staging states (for multi-stage rockets) */
    RocketState_STAGE_SEPARATION = 50, /* Stage separation detected */
    RocketState_STAGE_IGNITION = 51, /* Subsequent stage ignition */
    /* Recovery states */
    RocketState_TOUCHDOWN = 60, /* Ground impact detected */
    RocketState_LANDED = 61, /* On ground, stable */
    RocketState_RECOVERY = 62, /* Being recovered by team */
    /* Abort/failure states */
    RocketState_ABORT = 70, /* Launch abort */
    RocketState_FAILURE = 71, /* General failure detected */
    RocketState_CRASH = 72, /* Crash detected */
    /* Additional specialized states */
    RocketState_MACH_TRANSITION = 80, /* Transitioning through Mach 1 */
    RocketState_SUSTAINER_IGNITION = 81, /* Sustainer motor ignition */
    RocketState_BOOSTER_SEPARATION = 82, /* Booster separation for multi-stage */
    RocketState_AIR_START = 83 /* Air-start motor ignition */
} RocketState;

/* Struct definitions */
/* Protocol Buffer definition for sensor data */
typedef struct _SensorReading {
    uint32_t timestamp;
    uint32_t sequence;
    uint32_t device_id;
    RocketError error_code;
    RocketState rocket_state;
    /* Battery data */
    float battery_voltage;
    float battery_current;
    /* Accelerometer data */
    float accel_x;
    float accel_y;
    float accel_z;
    /* Gyroscope data */
    float gyro_x;
    float gyro_y;
    float gyro_z;
    /* Magnetometer data */
    float mag_x;
    float mag_y;
    float mag_z;
    /* GPS data */
    float gps_latitude;
    float gps_longitude;
    float gps_altitude;
    float gps_speed;
    int32_t gps_satellites;
    float gps_hdop;
    /* Barometer data */
    float baro_pressure;
    float baro_temperature;
} SensorReading;

/* We can add a container message for future expansion */
typedef struct _SensorDataBatch {
    pb_callback_t readings;
} SensorDataBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RocketError_MIN RocketError_NONE
#define _RocketError_MAX RocketError_UNKNOWN
#define _RocketError_ARRAYSIZE ((RocketError)(RocketError_UNKNOWN+1))

#define _RocketState_MIN RocketState_ERROR
#define _RocketState_MAX RocketState_AIR_START
#define _RocketState_ARRAYSIZE ((RocketState)(RocketState_AIR_START+1))

#define SensorReading_error_code_ENUMTYPE RocketError
#define SensorReading_rocket_state_ENUMTYPE RocketState



/* Initializer values for message structs */
#define SensorReading_init_default               {0, 0, 0, _RocketError_MIN, _RocketState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SensorDataBatch_init_default             {{{NULL}, NULL}}
#define SensorReading_init_zero                  {0, 0, 0, _RocketError_MIN, _RocketState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SensorDataBatch_init_zero                {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SensorReading_timestamp_tag              1
#define SensorReading_sequence_tag               2
#define SensorReading_device_id_tag              3
#define SensorReading_error_code_tag             4
#define SensorReading_rocket_state_tag           5
#define SensorReading_battery_voltage_tag        6
#define SensorReading_battery_current_tag        7
#define SensorReading_accel_x_tag                8
#define SensorReading_accel_y_tag                9
#define SensorReading_accel_z_tag                10
#define SensorReading_gyro_x_tag                 11
#define SensorReading_gyro_y_tag                 12
#define SensorReading_gyro_z_tag                 13
#define SensorReading_mag_x_tag                  14
#define SensorReading_mag_y_tag                  15
#define SensorReading_mag_z_tag                  16
#define SensorReading_gps_latitude_tag           17
#define SensorReading_gps_longitude_tag          18
#define SensorReading_gps_altitude_tag           19
#define SensorReading_gps_speed_tag              20
#define SensorReading_gps_satellites_tag         21
#define SensorReading_gps_hdop_tag               22
#define SensorReading_baro_pressure_tag          23
#define SensorReading_baro_temperature_tag       24
#define SensorDataBatch_readings_tag             1

/* Struct field encoding specification for nanopb */
#define SensorReading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          2) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    error_code,        4) \
X(a, STATIC,   SINGULAR, UENUM,    rocket_state,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_current,   7) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_x,           8) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_y,           9) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_z,          10) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,           11) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,           12) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,           13) \
X(a, STATIC,   SINGULAR, FLOAT,    mag_x,            14) \
X(a, STATIC,   SINGULAR, FLOAT,    mag_y,            15) \
X(a, STATIC,   SINGULAR, FLOAT,    mag_z,            16) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_latitude,     17) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_longitude,    18) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_altitude,     19) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_speed,        20) \
X(a, STATIC,   SINGULAR, INT32,    gps_satellites,   21) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_hdop,         22) \
X(a, STATIC,   SINGULAR, FLOAT,    baro_pressure,    23) \
X(a, STATIC,   SINGULAR, FLOAT,    baro_temperature,  24)
#define SensorReading_CALLBACK NULL
#define SensorReading_DEFAULT NULL

#define SensorDataBatch_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  readings,          1)
#define SensorDataBatch_CALLBACK pb_default_field_callback
#define SensorDataBatch_DEFAULT NULL
#define SensorDataBatch_readings_MSGTYPE SensorReading

extern const pb_msgdesc_t SensorReading_msg;
extern const pb_msgdesc_t SensorDataBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorReading_fields &SensorReading_msg
#define SensorDataBatch_fields &SensorDataBatch_msg

/* Maximum encoded size of messages (where known) */
/* SensorDataBatch_size depends on runtime parameters */
#define SENSOR_DATA_PB_H_MAX_SIZE                SensorReading_size
#define SensorReading_size                       133

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
